# .github/release-drafter.yml

name-template: 'v$NEXT_PATCH_VERSION 🎉'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'

  - title: '🛠 Frameworks and Tools'
    labels:
      - 'framework'
      - 'enhancement'

  - title: '🤖 Maintenance and Automation'
    labels:
      - 'chore'
      - 'infra'
      - 'maintenance'

  - title: '📚 Documentation and Website'
    labels:
      - 'documentation'
      - 'docs'
      - 'website'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPO/compare/$PREVIOUS_TAG...$NEW_TAG  