# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
    ruby: "3.3"

  commands:
    - python website/scripts/sync_docs.py
    - cd website
    - gem install bundler
    - bundle install
    # Use both _config.yml and _config_rtd.yml.
    # Settings in _config_rtd.yml will override _config.yml
    - bundle exec jekyll build --config _config.yml,_config_rtd.yml --destination ../_readthedocs/html