name: Markdown Link Check

on:
  pull_request:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          # Only check modified files for PRs
          check-modified-files-only: ${{ github.event_name == 'pull_request' && 'yes' || 'no' }}
          # For scheduled runs, check all files with verbose output
          use-verbose-mode: ${{ github.event_name == 'schedule' && 'yes' || 'no' }}  