name: Unit Tests

on:
  pull_request:
    paths:
      - 'gofannon/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra: ["testing", "langchain", "smolagents", "headless_browser", "google", "aws", "langflow"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3
          poetry --version

      - name: Install base dependencies
        run: poetry install --no-extras

      - name: Handle extra dependencies
        if: matrix.extra != 'langflow'
        run: poetry install --extras "${{ matrix.extra }}"

      - name: Special handling for langflow
        if: matrix.extra == 'langflow'
        run: pip install "langflow>=1.2.0,<2.0.0"

      - name: Run Tests
        run: |
          poetry run pytest tests/unit/${{ matrix.extra }}/  