name: Unit Tests

on:
  pull_request:
    paths:
      - 'gofannon/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extra: ["langchain", "smolagents", "headless_browser", "google", "aws", "langflow", "mcp"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  
          poetry --version  

      - name: Install dependencies with ${{ matrix.extra }}
        run: |
          poetry install --extras "${{ matrix.extra }}" --with dev

      - name: Run ${{ matrix.extra }} tests
        run: |
          test_path="tests/unit/${{ matrix.extra }}"
          if [ -d "$test_path" ]; then  
            poetry run pytest $test_path/ -v  
          else  
            echo "Warning: No tests found for ${{ matrix.extra }} at $test_path"  
          fi  